src/Entity/Search.php
<?php

namespace MyDigitalEnvironment\AlertsBundle\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use MyDigitalEnvironment\AlertsBundle\Enum\DocumentAccess;
use MyDigitalEnvironment\AlertsBundle\Enum\Platform;
use MyDigitalEnvironment\AlertsBundle\Enum\UpdateFrequency;
use MyDigitalEnvironment\AlertsBundle\MyDigitalEnvironmentAlertsBundle;
use MyDigitalEnvironment\AlertsBundle\Repository\SearchRepository;
use MyDigitalEnvironment\MyDigitalEnvironmentBundle\Entity\User;

// We stop using schema parameter, problems with postgresql and unsure on how to dynamically detect the DB for this use case

#[ORM\Table(name: MyDigitalEnvironmentAlertsBundle::TABLE_SCHEMA . '_search')]
#[ORM\Entity(repositoryClass: SearchRepository::class)]
class Search
{
    // todo : better name ?
    //  SearchAlert ? Alert ?

    const RESULT_CAP = 100;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $query = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $advancedQuery = null;

    /** @var Platform[] */
    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true, enumType: Platform::class)]
    private array $platforms = [];

    /** @var DocumentAccess[] */
    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    private ?array $access = [];

    #[ORM\Column(nullable: true)]
    private ?int $fromPublication = null;

    #[ORM\Column(nullable: true)]
    private ?int $untilPublication = null;

    /** @var ?string[] */
    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    private ?array $translations = [];

    /** @var ?string[] */
    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    private ?array $authors = [];

    /** @var ?string[] */
    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    private ?array $journalsPublications = [];

    /** @var ?string[] */
    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    private ?array $booksPublications = [];

    /** @var ?string[] */
    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    private ?array $hypothesesPublications = [];

    /** @var ?string[] */
    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    private ?array $types = [];

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $subscriber = null;

    /** @var ?string Identifier for the last result acknowledged by the user */
    #[ORM\Column(length: 2048, nullable: true)]
    private ?string $userAnchor = null;

    /** @var ?string Identifier for the last result acknowledged by the server */
    #[ORM\Column(length: 2048, nullable: true)]
    private ?string $updateAnchor = null;

    #[ORM\Column(options: ['default' => 0])]
    private int $newResultCount = 0;

    /** @var bool Is there more result for this search than the API could find with a first call ? */
    #[ORM\Column(options: ['default' => false])]
    private bool $moreResultThanCap = false;

    /** @var ?int<0, max> How many documents was queries in last update query */
    #[ORM\Column(nullable: true)]
    private ?int $queryCap = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $lastQueryDate = null;

    #[ORM\Column(enumType: UpdateFrequency::class, options: ['default' => UpdateFrequency::DAILY])]
    private UpdateFrequency $frequency = UpdateFrequency::DAILY;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(options: ['default' => true])]
    private ?bool $sendEmail = true;

    public function __construct()
    {
    }

    public function getResultCounter(): string
    {
        $count = (string) $this->newResultCount;
        return $this->moreResultThanCap ? $count.'+' : $count;
    }

    public function getDescription(): string
    {
        return $this->name !== null
            ? $this->name
            : $this->getLongDescription();
    }

    public function getLongDescription(): string
    {
        $d = [];
        if ($this->query !== null) {
            $d[] = "q=\"$this->query\"";
        }
        if ($this->platforms !== []) {
            $d[] = "pf=" . join(',', array_map(fn($p) => $p->value, $this->platforms));
        }
        if ($this->fromPublication !== null) {
            $d[] = "from=$this->fromPublication";
        }
        if ($this->untilPublication !== null) {
            $d[] = "until=$this->untilPublication";
        }

        // todo: fall back or alert log if empty ?
        return join(' and ', $d);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getQuery(): ?string
    {
        return $this->query;
    }

    public function setQuery(?string $query): static
    {
        $this->query = $query;

        return $this;
    }

    public function getAdvancedQuery(): ?string
    {
        return $this->advancedQuery;
    }

    public function setAdvancedQuery(?string $advancedQuery): static
    {
        $this->advancedQuery = $advancedQuery;

        return $this;
    }

    public function getPlatforms(): ?array
    {
        return $this->platforms;
    }

    public function setPlatforms(array $platforms): static
    {
        $this->platforms = $platforms;

        return $this;
    }

    public function getAccess(): ?array
    {
        return $this->access;
    }

    public function setAccess(array $access): static
    {
        $this->access = $access;

        return $this;
    }

    public function getFromPublication(): ?int
    {
        return $this->fromPublication;
    }

    public function setFromPublication(?int $fromPublication): static
    {
        $this->fromPublication = $fromPublication;

        return $this;
    }

    public function getUntilPublication(): ?int
    {
        return $this->untilPublication;
    }

    public function setUntilPublication(?int $untilPublication): static
    {
        $this->untilPublication = $untilPublication;

        return $this;
    }

    public function getTranslations(): ?array
    {
        return $this->translations;
    }

    public function setTranslations(array $translations): static
    {
        $this->translations = $translations;

        return $this;
    }

    public function getAuthors(): ?array
    {
        return $this->authors;
    }

    public function setAuthors(array $authors): static
    {
        $this->authors = $authors;

        return $this;
    }

    public function getJournalsPublications(): ?array
    {
        return $this->journalsPublications;
    }

    public function setJournalsPublications(?array $journalsPublications): static
    {
        $this->journalsPublications = $journalsPublications;

        return $this;
    }

    public function getBooksPublications(): ?array
    {
        return $this->booksPublications;
    }

    public function setBooksPublications(?array $booksPublications): static
    {
        $this->booksPublications = $booksPublications;

        return $this;
    }

    public function getHypothesesPublications(): ?array
    {
        return $this->hypothesesPublications;
    }

    public function setHypothesesPublications(?array $hypothesesPublications): static
    {
        $this->hypothesesPublications = $hypothesesPublications;

        return $this;
    }

    public function getTypes(): ?array
    {
        return $this->types;
    }

    public function setTypes(array $types): static
    {
        $this->types = $types;

        return $this;
    }

    public function getSubscriber(): ?User
    {
        return $this->subscriber;
    }

    public function setSubscriber(?User $subscriber): static
    {
        $this->subscriber = $subscriber;

        return $this;
    }

    public function getUserAnchor(): ?string
    {
        return $this->userAnchor;
    }

    public function setUserAnchor(?string $userAnchor): static
    {
        $this->userAnchor = $userAnchor;

        return $this;
    }

    public function getNewResultCount(): ?int
    {
        return $this->newResultCount;
    }

    public function setNewResultCount(?int $newResultCount): static
    {
        $this->newResultCount = $newResultCount;

        return $this;
    }

    public function isMoreResultThanCap(): ?bool
    {
        return $this->moreResultThanCap;
    }

    public function setMoreResultThanCap(bool $moreResultThanCap): static
    {
        $this->moreResultThanCap = $moreResultThanCap;

        return $this;
    }

    public function getQueryCap(): ?int
    {
        return $this->queryCap;
    }

    public function setQueryCap(int $queryCap): static
    {
        $this->queryCap = $queryCap;

        return $this;
    }

    public function getLastQueryDate(): ?\DateTimeInterface
    {
        return $this->lastQueryDate;
    }

    public function setLastQueryDate(?\DateTimeInterface $lastQueryDate): static
    {
        $this->lastQueryDate = $lastQueryDate;

        return $this;
    }

    public function getFrequency(): UpdateFrequency
    {
        return $this->frequency;
    }

    public function setFrequency(UpdateFrequency $frequency): static
    {
        $this->frequency = $frequency;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function canSendEmail(): ?bool
    {
        return $this->sendEmail;
    }

    public function setSendEmail(bool $sendEmail): static
    {
        $this->sendEmail = $sendEmail;

        return $this;
    }

    public function getUpdateAnchor(): ?string
    {
        return $this->updateAnchor;
    }

templates/search/_base.html.twig
{% extends '@MyDigitalEnvironment/base.html.twig' %}
{% trans_default_domain 'my-de-alerts' %}

{% block title %}My Digital Environment | {{ 'alerts.title'|trans }}{% endblock %}
{% block navTitle %}{% endblock %}

{# Todo : update how we define the path/navBrand extension here, should not be a long term solution #}
{% block brandExpansion %}
    <span class="me-1" style="margin-left: -.75rem !important;">/</span>
    <a class="navbar-brand mb-0 h1"
       style=" color: #d77600;"
       href="{{ path('my_digital_environment_alerts_hub') }}">
        {{ 'alerts.nav_title'|trans }}
    </a>
{% endblock %}

templates/search/hub.html.twig
{% extends '@MyDigitalEnvironmentAlerts/search/_base.html.twig' %}
{% trans_default_domain 'my-de-alerts' %}

{% block title %}My Digital Environment | {{ 'alerts.title'|trans }}{% endblock %}
{% block navTitle %}{{ 'alerts.title'|trans }}{% endblock %}


{% block javascripts %}
    <script>
        function setDeleteModalEvent(modal) {
            modal.addEventListener('show.bs.modal', event => {
                const link = event.relatedTarget;
                modal.querySelector('#confirm-deletion').href = link.href;
                modal.querySelector('#delete-search-name').innerHTML = link.getAttribute('data-bs-name');
            })
        }

        function seekDeleteModal(loopIndex = 0) {
            if (loopIndex >= 20) return;
            let modal = document.getElementById('deleteAlertModal');
            if (modal === null) {
                setTimeout(seekDeleteModal, 25, ++loopIndex);
            } else {
                setDeleteModalEvent(modal)
            }
        }

        seekDeleteModal()
    </script>
{% endblock %}

{% block content %}
    <a href="{{ path('my_digital_environment_alerts_new_search') }}" class="btn btn-primary mb-3" role="button">{{ 'alerts.new'|trans }}</a>
    <p>{{ 'alerts.count'|trans({'alerts': searches|length})|raw }}</p>
    {% for search in searches %}
        {# sizing not great, would not work with mobile #}
        <div class="list-group list-group-horizontal"> {# flex-fill #}
            <a href="{{ path('my_digital_environment_alerts_delete_search', {'id': search.id}) }}"
               class="list-group-item list-group-item-action w-auto text-danger flex-fill align-content-center"
               data-bs-toggle="modal" data-bs-target="#deleteAlertModal" data-bs-name="{{ search.description }}"
            >
                {{ 'alerts.delete'|trans }}
            </a>
            <a href="{{ path('my_digital_environment_alerts_edit_search', {'id': search.id}) }}"
               class="list-group-item list-group-item-action w-auto text-primary flex-fill align-content-center">{{ 'alerts.edit'|trans }}</a>
            {{ _self.resultCount(search) }}
            <div class="list-group-item align-content-center" style="width: 100%">
                <span {% if search.name is not null %}title="{{ search.longDescription }}"{% endif %}>{{ search.description }}</span>
                <br>
                <span class="fw-light fst-italic text-secondary">
                    {{ 'alerts.next_update_date'|trans({'dt': search.lastQueryDate|date_modify("+"~search.frequency.value~" day")}) }}
                </span>
            </div>
        </div>
    {% endfor %}

    <!-- Modal -->
    <div class="modal fade" id="deleteAlertModal" tabindex="-1" aria-labelledby="deleteAlertModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteAlertModalLabel">
                        {{ 'alerts.delete_modal.h1'|trans }}
                    </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ 'alerts.delete_modal.ask'|trans|raw }}
                    <br>
                    <b id="delete-search-name" class="text-center d-block"></b>
                    <br>
                    {{ 'alerts.delete_modal.danger'|trans|raw }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        {{ 'alerts.delete_modal.cancel'|trans }}
                    </button>
                    <a id="confirm-deletion" href="https://example.com" type="button" class="btn btn-danger">
                        {{ 'alerts.delete_modal.delete'|trans }}
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{# @var search \MyDigitalEnvironment\AlertsBundle\Entity\Search #}
{% macro resultCount(search) %}
    {% if search.canSendEmail %}
        <div class="list-group-item align-content-center text-center" style="color: gray; text-wrap: nowrap">
            {{ 'alert.results.email'|trans|raw }}
        </div>
    {% elseif search.newResultCount <= 0 %}
        <div class="list-group-item align-content-center text-center" style="color: gray; text-wrap: nowrap">
            {{ 'alerts.results.none'|trans }}
        </div>
    {% else %}
        <a href="{{ path('my_digital_environment_alerts_get_search_results', {'id': search.id}) }}" style="text-wrap: nowrap;"
           class="list-group-item list-group-item-action w-auto flex-fill align-content-center text-success text-center fw-bold">
            {% if search.moreResultThanCap %}
                {{ 'alerts.results.more_than'|trans({'count': search.newResultCount})|raw }}
            {% else %}
                {{ 'alerts.results.count'|trans({'count': search.newResultCount})|raw }}
            {% endif %}
        </a>
    {% endif %}
{% endmacro %}

templates/search/new.html.twig
{% extends '@MyDigitalEnvironmentAlerts/search/_base.html.twig' %}
{% trans_default_domain 'my-de-alerts' %}

{# todo: change page title when editing an pre-existing alert #}
{% block title %}My Digital Environment | {{ 'alerts.title'|trans }} | {{ 'alerts.title.new'|trans }}{% endblock %}
{% block navTitle %}{{ 'alerts.title.new'|trans }}{% endblock %}

{% block content %}
    {{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.name) }}
    {{ form_row(form.query) }}
    {{ form_row(form.platforms) }}
    {{ form_row(form.fromPublication) }}
    {{ form_row(form.untilPublication) }}
    {{ form_row(form.frequency) }}
    {{ form_row(form.sendEmail) }}
    {# todo: find ways to change to what's shown ('MONTHLY' => 'every 28 days') and to radio form #}

    <div class="d-flex gap-2">
        {{ form_widget(form.save) }}
        {{ form_widget(form.preview, {'attr': {'formaction': path('my_digital_environment_alerts_preview_search')}}) }}
    </div>
    {% do form.edit.setRendered() %}
    {# todo : add delete button when search is saved in db (look at id?) #}
    {{ form_rest(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/search/preview.html.twig
{% extends '@MyDigitalEnvironmentAlerts/search/_base.html.twig' %}
{% trans_default_domain 'my-de-alerts' %}

{% block title %}My Digital Environment | {{ 'alerts.title'|trans }} | {{ 'alerts.title.preview'|trans }}{% endblock %}
{% block navTitle %}{{ 'alerts.title.preview.long'|trans }} <i>{{ search.description }}</i>{% endblock %}

{% block content %}
    {{ form_start(form) }}

    {{ form_row(form.query) }}
    <div class="d-flex flex-row align-items-center mb-2 gap-2 justify-content-evenly">
        {% set editUrl = path('my_digital_environment_alerts_new_search') %}
        {{ form_widget(form.preview, {'label': 'alerts.form.refresh'}) }}
        {{ form_widget(form.edit) }}
        {{ form_widget(form.save) }}
        <div>
            {{ 'alerts.preview.paginator'|trans({
                'total': result.pagination.totalDocumentCount,
                'currentPage': result.pagination.currentPage,
                'pageCount': result.pagination.pageCount
            })|raw }}
        </div>
    </div>
    {{ form_end(form) }}
    <div class="list-group gap-3">
        {% for document in result.documents %}

            {% set pColor = 'rgb(0, 0, 0)' %}
            {% if document.platform.value == 'OB' %}
                {% set pColor = 'rgb(183, 50, 136)' %}
            {% elseif document.platform.value == 'OJ' %}
                {% set pColor = 'rgb(11, 183, 217)' %}
            {% elseif document.platform.value == 'CO' %}
                {% set pColor = 'rgb(141, 190, 30)' %}
            {% elseif document.platform.value == 'HO' %}
                {% set pColor = 'rgb(236, 90, 79)' %}
            {% endif %}

            <a class="list-group-item list-group-item-action p-0 border rounded pb-2 shadow"
               href="{{ document.url }}"
               target="_blank">
                <div class="px-2 py-1">
                    {{ _self.platformName(document.platform.value) }}
                    {% if document.site is not null %}
                        <b style="color: {{ pColor }}">/</b>
                        <i>{{ document.site }}</i>
                    {% endif %}
                </div>
                <div class="d-flex flex-row px-2 pt-1 border-top border-3 gap-2"
                     style="border-color: {{ pColor }} !important">
                    <div class="flex-fill d-flex flex-column">
                        <b style="color: {{ pColor }}">{{ document.title }}</b>
                        {% if document.subtitle is not null %}
                            <i>{{ document.subtitle }}</i>
                        {% endif %}
                        {% if document.overview is not null %}
                            <p class="m-0">{{ document.overview }}</p>
                        {% endif %}
                        {% if document.type is not null %}
                            <span style="color: grey">{{ document.type | upper }}</span>
                        {% endif %}
                    </div>
                    <div>
                        {{ _self.authors(document) }}
                    </div>
                </div>
                {# {% if document.overview is not null %} #}
                {#     <br/><span style="color: dimgrey">{{ document.overview }}</span> #}
                {# {% endif %} #}
            </a>
        {% endfor %}
    </div>
    <br/>
    {# {{ dump(result.pagination) }} #}
    {# {{ dump(result.documents) }} #}
    {# {{ dump(result.documents.0) }} #}
{% endblock %}


{% macro authors(document) %}
    {% if document.authors is not null and document.authors is not empty %}
        <div class="d-flex flex-column">
            {% for author in document.authors %}
                <u class="text-nowrap" style="text-align:end;">{{ author }}</u>
                {% if not loop.last %}<br>{% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% endmacro %}

{% macro platformName(platformId) %}
    {% if platformId == 'OB' %}
        {{ 'platform.books'|trans }}
    {% elseif platformId == 'OJ' %}
        {{ 'platform.journals'|trans }}
    {% elseif platformId == 'CO' %}
        {{ 'platform.calenda'|trans }}
    {% elseif platformId == 'HO' %}
        {{ 'platform.hypotheses'|trans }}
    {% endif %}
{% endmacro %}

templates/search/results.html.twig
{% extends '@MyDigitalEnvironmentAlerts/search/_base.html.twig' %}
{% trans_default_domain 'my-de-alerts' %}

{% block title %}My Digital Environment | {{ 'alerts.title'|trans }} | {{ 'alerts.title.results'|trans }}{% endblock %}
{% block navTitle %}{{ 'alerts.title.results.long'|trans }} {{ search.description }}{% endblock %}

{% block content %}
    <div class="list-group gap-3">
        {% for document in documents %}

            {% set pColor = 'rgb(0, 0, 0)' %}
            {% if document.platform.value == 'OB' %}
                {% set pColor = 'rgb(183, 50, 136)' %}
            {% elseif document.platform.value == 'OJ' %}
                {% set pColor = 'rgb(11, 183, 217)' %}
            {% elseif document.platform.value == 'CO' %}
                {% set pColor = 'rgb(141, 190, 30)' %}
            {% elseif document.platform.value == 'HO' %}
                {% set pColor = 'rgb(236, 90, 79)' %}
            {% endif %}

            <a class="list-group-item list-group-item-action p-0 border rounded pb-2 shadow"
               href="{{ document.url }}"
               target="_blank">
                <div class="px-2 py-1">
                    {{ _self.platformName(document.platform.value) }}
                    {% if document.site is not null %}
                        <b style="color: {{ pColor }}">/</b>
                        <i>{{ document.site }}</i>
                    {% endif %}
                </div>
                <div class="d-flex flex-row px-2 pt-1 border-top border-3 gap-2"
                     style="border-color: {{ pColor }} !important">
                    <div class="flex-fill d-flex flex-column">
                        <b style="color: {{ pColor }}">{{ document.title }}</b>
                        {% if document.subtitle is not null %}
                            <i>{{ document.subtitle }}</i>
                        {% endif %}
                        {% if document.overview is not null %}
                            <p class="m-0">{{ document.overview }}</p>
                        {% endif %}
                        {% if document.type is not null %}
                            <span style="color: grey">{{ document.type | upper }}</span>
                        {% endif %}
                    </div>
                    <div>
                        {{ _self.authors(document) }}
                    </div>
                </div>
                {# {% if document.overview is not null %} #}
                {#     <br/><span style="color: dimgrey">{{ document.overview }}</span> #}
                {# {% endif %} #}
            </a>
        {% endfor %}
    </div>
    <br/>
    {# {{ dump(result.pagination) }} #}
    {# {{ dump(result.documents) }} #}
    {# {{ dump(result.documents.0) }} #}
{% endblock %}


{% macro authors(document) %}
    {% if document.authors is not null and document.authors is not empty %}
        <div class="d-flex flex-column">
            {% for author in document.authors %}
                <u class="text-nowrap" style="text-align:end;">{{ author }}</u>
                {% if not loop.last %}<br>{% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% endmacro %}

{% macro platformName(platformId) %}
    {% if platformId == 'OB' %}
        {{ 'platform.books'|trans }}
    {% elseif platformId == 'OJ' %}
        {{ 'platform.journals'|trans }}
    {% elseif platformId == 'CO' %}
        {{ 'platform.calenda'|trans }}
    {% elseif platformId == 'HO' %}
        {{ 'platform.hypotheses'|trans }}
    {% endif %}
{% endmacro %}